#!/usr/bin/env bash
set -euo pipefail

REPO_SLUG="${1:-}"
REF="${2:-main}"

infer_repo_slug() {
  local url
  url="$(git config --get remote.origin.url || true)"

  case "$url" in
    git@github.com:*)
      url="${url#git@github.com:}"
      url="${url%.git}"
      printf '%s\n' "$url"
      return 0
      ;;
    https://github.com/*)
      url="${url#https://github.com/}"
      url="${url%.git}"
      printf '%s\n' "$url"
      return 0
      ;;
  esac

  return 1
}

if [ -z "$REPO_SLUG" ]; then
  REPO_SLUG="$(infer_repo_slug || true)"
fi

[ -n "$REPO_SLUG" ] || {
  echo "usage: generate-skills-index.sh [owner/repo] [ref]" >&2
  exit 1
}

mkdir -p skills

{
  echo "# Skills Catalog"
  echo
  echo "This file is generated by scripts/generate-skills-index.sh."
  echo
  echo "## Install Prerequisite"
  echo
  echo "Use OpenClaw workspace as current directory, then run:"
  echo
  echo "curl -fsSL https://raw.githubusercontent.com/${REPO_SLUG}/${REF}/scripts/install-skill-from-github.sh | bash -s -- ${REPO_SLUG} <skill-folder> ${REF} <workspace>"
  echo
  echo "## Skills"
  echo
  echo "| Skill Folder | Name | Description | View | Install |"
  echo "|---|---|---|---|---|"

  found=0
  for skill_md in skills/*/SKILL.md; do
    [ -f "$skill_md" ] || continue
    found=1

    skill_folder="$(basename "$(dirname "$skill_md")")"

    name="$(awk '
      NR==1 && $0=="---" {fm=1; next}
      fm && $0=="---" {exit}
      fm && $1=="name:" {sub(/^name:[[:space:]]*/, ""); print; exit}
    ' "$skill_md")"

    description="$(awk '
      NR==1 && $0=="---" {fm=1; next}
      fm && $0=="---" {exit}
      fm && $1=="description:" {
        sub(/^description:[[:space:]]*/, "")
        print
        exit
      }
    ' "$skill_md")"

    [ -n "$name" ] || name="$skill_folder"
    [ -n "$description" ] || description="(no description)"
    description="${description//|/\\|}"

    view_link="https://github.com/${REPO_SLUG}/tree/${REF}/skills/${skill_folder}"
    install_cmd="curl -fsSL https://raw.githubusercontent.com/${REPO_SLUG}/${REF}/scripts/install-skill-from-github.sh | bash -s -- ${REPO_SLUG} ${skill_folder} ${REF} <workspace>"

    printf '| `%s` | `%s` | %s | [View](%s) | `%s` |\n' \
      "$skill_folder" "$name" "$description" "$view_link" "$install_cmd"
  done

  if [ "$found" -eq 0 ]; then
    echo "| _none_ | _none_ | No skills yet. Add folders under skills/<skill>/SKILL.md. | - | - |"
  fi
} > skills/INDEX.md

echo "Generated skills/INDEX.md for ${REPO_SLUG}@${REF}"
